export const SHIPPING_FEE_CHANGE = "SHIPPING_FEE_CHANGE";
export const SHIPPING_FEE_REQUEST = "SHIPPING_FEE_REQUEST";
export const SHIPPING_FEE_SUCCESS = "SHIPPING_FEE_SUCCESS";
export const SHIPPING_FEE_FAIL = "SHIPPING_FEE_FAIL";

export const SHIPPING_ADDRESS_SAVE = "SHIPPING_ADDRESS_SAVE";
export const ORDER_FORM_SHIPPING_SAVE = "ORDER_FORM_SHIPPING_SAVE";