export const SHIPPING_FEE_CHANGE = "SHIPPING_FEE_CHANGE";
export const SHIPPING_FEE_REQUEST = "SHIPPING_FEE_REQUEST";
export const SHIPPING_FEE_SUCCESS = "SHIPPING_FEE_SUCCESS";
export const SHIPPING_FEE_FAIL = "SHIPPING_FEE_FAIL";