export const GET_BESTSELLERS_REQUEST = "GET_BESTSELLERS_REQUEST";
export const GET_BESTSELLERS_SUCCESS = "GET_BESTSELLERS_SUCCESS";
export const GET_BESTSELLERS_FAIL = "GET_BESTSELLERS_FAIL";

export const GET_RECOMMENDED_REQUEST = "GET_RECOMMENDED_REQUEST";
export const GET_RECOMMENDED_SUCCESS = "GET_RECOMMENDED_SUCCESS";
export const GET_RECOMMENDED_FAIL = "GET_RECOMMENDED_FAIL";

export const GET_CART_REQUEST = "GET_CART_REQUEST";
