export const GET_BESTSELLERS_REQUEST = "GET_BESTSELLERS_REQUEST";
export const GET_BESTSELLERS_SUCCESS = "GET_BESTSELLERS_SUCCESS";
export const GET_BESTSELLERS_FAIL = "GET_BESTSELLERS_FAIL";

export const GET_RECOMMENDEDS_REQUEST = "GET_RECOMMENDEDS_REQUEST";
export const GET_RECOMMENDEDS_SUCCESS = "GET_RECOMMENDEDS_SUCCESS";
export const GET_RECOMMENDEDS_FAIL = "GET_RECOMMENDEDS_FAIL";

export const GET_CART_REQUEST = "GET_CART_REQUEST";

export const ADD_CART_LOCAL = "ADD_CART_LOCAL";
export const ADD_CART_MULTI_LOCAL = "ADD_CART_MULTI_LOCAL";
export const UPDATE_CART_LOCAL = "UPDATE_CART_LOCAL";
export const REMOVE_CART_LOCAL = "REMOVE_CART_LOCAL";
export const REMOVE_ALL_CART_LOCAL = "REMOVE_ALL_CART_LOCAL";

export const SAVE_CART_REQUEST = "SAVE_CART_REQUEST";
export const SAVE_CART_SUCCESS = "SAVE_CART_SUCCESS";
export const SAVE_CART_FAIL = "SAVE_CART_FAIL";

export const VIEW_PRODUCT_REQUEST = "VIEW_PRODUCT_REQUEST";
export const VIEW_PRODUCT_SUCCESS = "VIEW_PRODUCT_SUCCESS";
export const VIEW_PRODUCT_FAIL = "VIEW_PRODUCT_FAIL";

export const VIEW_STORE_REQUEST = "VIEW_STORE_REQUEST";
export const VIEW_STORE_SUCCESS = "VIEW_STORE_SUCCESS";
export const VIEW_STORE_FAIL = "VIEW_STORE_FAIL";

export const BOOK_GENRES_REQUEST = "BOOK_GENRES_REQUEST";
export const BOOK_GENRES_SUCCESS = "BOOK_GENRES_SUCCESS";
export const BOOK_GENRES_FAIL = "BOOK_GENRES_FAIL";

