export const GET_BESTSELLERS_REQUEST = "GET_BESTSELLERS_REQUEST";
export const GET_BESTSELLERS_SUCCESS = "GET_BESTSELLERS_SUCCESS";
export const GET_BESTSELLERS_FAIL = "GET_BESTSELLERS_FAIL";

export const GET_RECOMMENDED_REQUEST = "GET_RECOMMENDED_REQUEST";
export const GET_RECOMMENDED_SUCCESS = "GET_RECOMMENDED_SUCCESS";
export const GET_RECOMMENDED_FAIL = "GET_RECOMMENDED_FAIL";

export const GET_CART_REQUEST = "GET_CART_REQUEST";

export const ADD_CART_LOCAL = "ADD_CART_LOCAL";
export const ADD_CART_MULTI_LOCAL = "ADD_CART_MULTI_LOCAL";
export const UPDATE_CART_LOCAL = "UPDATE_CART_LOCAL";
export const REMOVE_CART_LOCAL = "REMOVE_CART_LOCAL";

export const SAVE_CART_REQUEST = "SAVE_CART_REQUEST";
export const SAVE_CART_SUCCESS = "SAVE_CART_SUCCESS";
export const SAVE_CART_FAIL = "SAVE_CART_FAIL";

export const VIEW_PRODUCT_REQUEST = "VIEW_PRODUCT_REQUEST";
export const VIEW_PRODUCT_SUCCESS = "VIEW_PRODUCT_SUCCESS";
export const VIEW_PRODUCT_FAIL = "VIEW_PRODUCT_FAIL";

