export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";

export const USER_SIGNOUT = "USER_SIGNOUT";

export const CLEAR_USER_SIGNIN_ERRORS = "CLEAR_USER_SIGNIN_ERRORS";